project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Shreya Bansal: Selected Works"
  site-url: "https://sherya21.github.io/portfolio" 
  repo-url: "https://sherya21.github.com/portfolio"
  repo-actions: [source]
  description: "Data Analyst and Urban Planner"
  page-navigation: true
  back-to-top-navigation: true
  twitter-card: true
  search: 
    location: navbar
    type: overlay
  comments: 
    utterances: 
      repo: sherya21/sherya21.github.io/portfolio
      label: utterances
      theme: body-light
      issue-term: title
      

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    center: "[About me](/about.qmd)"
    left: "&copy; CC-Shreya Bansal 2024"
          
format:
  html:
    highlight-style: solarized
    theme: darkly
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    grid:
      body-width: 900px
      gutter-width: 0.1rem
    link-external-newwindow: true
    
execute: 
  freeze: auto
  cache: true
  